version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h6r8z9q9
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building Docker image...
      - docker build -t python-app .
      - docker tag python-app:latest public.ecr.aws/h6r8z9q9/python-app:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push public.ecr.aws/h6r8z9q9/python-app:latest

artifacts:
  bucket-name: codepipeline-us-east-1-547174674211
