version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update
      - apt-get install -y python3-pip
  pre_build:
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo "Starting Flask application..."
      - python3 app.py
artifacts:
  files:
    - '**/*'
